version: '3'
services:
  vuesplash_web:
    build: .
    volumes:
      - ./web:/var/www/html/vuesplash
    ports:
      - 8081:8081
      - 3000:3000
  vuesplash_db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - ./database:/var/lib/postgres/data
    ports:
      - 5434:5432
